cmake_minimum_required(VERSION 2.6)
	add_executable(exceptionCpp exceptionHandl.cpp
	assigntopCpp assignmentop.cpp
	bitwiseop bitwiseop.cpp
	catchCpp catch.cpp
	conditionalCpp conditionalCpp.cpp
	copyconstCpp copy_const.cpp
	privateCpp privateCpp.cpp
	publicCpp publicCpp.cpp)
